[package]
name = "kallen"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = { version = "0.4.28", features = ["serde"] }
clap = { version = "4.4.2", features = ["derive"] }
serde = { version = "1.0.188", features = ["derive"] }
serde_json = "1.0.105"
